package com.gusedu.model;
// Generated 05/01/2016 05:20:55 PM by Hibernate Tools 4.3.1



/**
 * EnfermedadVisita generated by hbm2java
 */
public class EnfermedadVisita  implements java.io.Serializable {


     private Integer exvCodigo;
     private Enfermedad enfermedad;
     private Visita visita;
     private String exvDescripcion;

    public EnfermedadVisita() {
    }

	
    public EnfermedadVisita(Enfermedad enfermedad, Visita visita) {
        this.enfermedad = enfermedad;
        this.visita = visita;
    }
    public EnfermedadVisita(Enfermedad enfermedad, Visita visita, String exvDescripcion) {
       this.enfermedad = enfermedad;
       this.visita = visita;
       this.exvDescripcion = exvDescripcion;
    }
   
    public Integer getExvCodigo() {
        return this.exvCodigo;
    }
    
    public void setExvCodigo(Integer exvCodigo) {
        this.exvCodigo = exvCodigo;
    }
    public Enfermedad getEnfermedad() {
        return this.enfermedad;
    }
    
    public void setEnfermedad(Enfermedad enfermedad) {
        this.enfermedad = enfermedad;
    }
    public Visita getVisita() {
        return this.visita;
    }
    
    public void setVisita(Visita visita) {
        this.visita = visita;
    }
    public String getExvDescripcion() {
        return this.exvDescripcion;
    }
    
    public void setExvDescripcion(String exvDescripcion) {
        this.exvDescripcion = exvDescripcion;
    }




}


