package com.gusedu.model;
// Generated 15/09/2015 11:54:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Enfermedad generated by hbm2java
 */
public class Enfermedad  implements java.io.Serializable {


     private Integer enfCodigo;
     private String enfNombre;
     private Set enfermedadPars = new HashSet(0);
     private Set enfermedadTerapias = new HashSet(0);
     private Set enfermedadVisitas = new HashSet(0);

    public Enfermedad() {
    }

    public Enfermedad(String enfNombre, Set enfermedadPars, Set enfermedadTerapias, Set enfermedadVisitas) {
       this.enfNombre = enfNombre;
       this.enfermedadPars = enfermedadPars;
       this.enfermedadTerapias = enfermedadTerapias;
       this.enfermedadVisitas = enfermedadVisitas;
    }
   
    public Integer getEnfCodigo() {
        return this.enfCodigo;
    }
    
    public void setEnfCodigo(Integer enfCodigo) {
        this.enfCodigo = enfCodigo;
    }
    public String getEnfNombre() {
        return this.enfNombre;
    }
    
    public void setEnfNombre(String enfNombre) {
        this.enfNombre = enfNombre;
    }
    public Set getEnfermedadPars() {
        return this.enfermedadPars;
    }
    
    public void setEnfermedadPars(Set enfermedadPars) {
        this.enfermedadPars = enfermedadPars;
    }
    public Set getEnfermedadTerapias() {
        return this.enfermedadTerapias;
    }
    
    public void setEnfermedadTerapias(Set enfermedadTerapias) {
        this.enfermedadTerapias = enfermedadTerapias;
    }
    public Set getEnfermedadVisitas() {
        return this.enfermedadVisitas;
    }
    
    public void setEnfermedadVisitas(Set enfermedadVisitas) {
        this.enfermedadVisitas = enfermedadVisitas;
    }




}


