package com.gusedu.model;
// Generated 18/02/2016 11:27:55 AM by Hibernate Tools 4.3.1



/**
 * EnfermedadTerapia generated by hbm2java
 */
public class EnfermedadTerapia  implements java.io.Serializable {


     private Integer extCodigo;
     private Enfermedad enfermedad;
     private Terapia terapia;
     private String extDescripcion;

    public EnfermedadTerapia() {
    }

	
    public EnfermedadTerapia(Enfermedad enfermedad, Terapia terapia) {
        this.enfermedad = enfermedad;
        this.terapia = terapia;
    }
    public EnfermedadTerapia(Enfermedad enfermedad, Terapia terapia, String extDescripcion) {
       this.enfermedad = enfermedad;
       this.terapia = terapia;
       this.extDescripcion = extDescripcion;
    }
   
    public Integer getExtCodigo() {
        return this.extCodigo;
    }
    
    public void setExtCodigo(Integer extCodigo) {
        this.extCodigo = extCodigo;
    }
    public Enfermedad getEnfermedad() {
        return this.enfermedad;
    }
    
    public void setEnfermedad(Enfermedad enfermedad) {
        this.enfermedad = enfermedad;
    }
    public Terapia getTerapia() {
        return this.terapia;
    }
    
    public void setTerapia(Terapia terapia) {
        this.terapia = terapia;
    }
    public String getExtDescripcion() {
        return this.extDescripcion;
    }
    
    public void setExtDescripcion(String extDescripcion) {
        this.extDescripcion = extDescripcion;
    }




}


