package com.gusedu.model;
// Generated 05/01/2016 05:20:55 PM by Hibernate Tools 4.3.1



/**
 * Foo generated by hbm2java
 */
public class Foo  implements java.io.Serializable {


     private Integer id;
     private short val;

    public Foo() {
    }

    public Foo(short val) {
       this.val = val;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public short getVal() {
        return this.val;
    }
    
    public void setVal(short val) {
        this.val = val;
    }




}


