package com.gusedu.model;
// Generated 15/09/2015 11:54:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private Integer gruCodigo;
     private String gruNombre;
     private Set pars = new HashSet(0);

    public Grupo() {
    }

    public Grupo(String gruNombre, Set pars) {
       this.gruNombre = gruNombre;
       this.pars = pars;
    }
   
    public Integer getGruCodigo() {
        return this.gruCodigo;
    }
    
    public void setGruCodigo(Integer gruCodigo) {
        this.gruCodigo = gruCodigo;
    }
    public String getGruNombre() {
        return this.gruNombre;
    }
    
    public void setGruNombre(String gruNombre) {
        this.gruNombre = gruNombre;
    }
    public Set getPars() {
        return this.pars;
    }
    
    public void setPars(Set pars) {
        this.pars = pars;
    }




}


