package com.gusedu.model;
// Generated 15/09/2015 11:54:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private Integer marCodigo;
     private String marNombre;
     private Set modelos = new HashSet(0);

    public Marca() {
    }

    public Marca(String marNombre, Set modelos) {
       this.marNombre = marNombre;
       this.modelos = modelos;
    }
   
    public Integer getMarCodigo() {
        return this.marCodigo;
    }
    
    public void setMarCodigo(Integer marCodigo) {
        this.marCodigo = marCodigo;
    }
    public String getMarNombre() {
        return this.marNombre;
    }
    
    public void setMarNombre(String marNombre) {
        this.marNombre = marNombre;
    }
    public Set getModelos() {
        return this.modelos;
    }
    
    public void setModelos(Set modelos) {
        this.modelos = modelos;
    }




}


