package com.gusedu.model;
// Generated 05/01/2016 05:20:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private Integer marCodigo;
     private String marNombre;
     private Set modelos = new HashSet(0);
     private Set modelos_1 = new HashSet(0);

    public Marca() {
    }

    public Marca(String marNombre, Set modelos, Set modelos_1) {
       this.marNombre = marNombre;
       this.modelos = modelos;
       this.modelos_1 = modelos_1;
    }
   
    public Integer getMarCodigo() {
        return this.marCodigo;
    }
    
    public void setMarCodigo(Integer marCodigo) {
        this.marCodigo = marCodigo;
    }
    public String getMarNombre() {
        return this.marNombre;
    }
    
    public void setMarNombre(String marNombre) {
        this.marNombre = marNombre;
    }
    public Set getModelos() {
        return this.modelos;
    }
    
    public void setModelos(Set modelos) {
        this.modelos = modelos;
    }
    public Set getModelos_1() {
        return this.modelos_1;
    }
    
    public void setModelos_1(Set modelos_1) {
        this.modelos_1 = modelos_1;
    }




}


