package com.gusedu.model;
// Generated 15/09/2015 11:54:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modelo generated by hbm2java
 */
public class Modelo  implements java.io.Serializable {


     private Integer modCodigo;
     private Marca marca;
     private String modYearFab;
     private String modColor;
     private String modNombre;
     private String modSize;
     private Set productos = new HashSet(0);

    public Modelo() {
    }

	
    public Modelo(Marca marca) {
        this.marca = marca;
    }
    public Modelo(Marca marca, String modYearFab, String modColor, String modNombre, String modSize, Set productos) {
       this.marca = marca;
       this.modYearFab = modYearFab;
       this.modColor = modColor;
       this.modNombre = modNombre;
       this.modSize = modSize;
       this.productos = productos;
    }
   
    public Integer getModCodigo() {
        return this.modCodigo;
    }
    
    public void setModCodigo(Integer modCodigo) {
        this.modCodigo = modCodigo;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public String getModYearFab() {
        return this.modYearFab;
    }
    
    public void setModYearFab(String modYearFab) {
        this.modYearFab = modYearFab;
    }
    public String getModColor() {
        return this.modColor;
    }
    
    public void setModColor(String modColor) {
        this.modColor = modColor;
    }
    public String getModNombre() {
        return this.modNombre;
    }
    
    public void setModNombre(String modNombre) {
        this.modNombre = modNombre;
    }
    public String getModSize() {
        return this.modSize;
    }
    
    public void setModSize(String modSize) {
        this.modSize = modSize;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


