package com.gusedu.model;
// Generated 18/02/2016 11:27:55 AM by Hibernate Tools 4.3.1



/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private Integer pagoCodigo;
     private TipoPago tipoPago;
     private Visita visita;
     private Double monto;

    public Pago() {
    }

    public Pago(TipoPago tipoPago, Visita visita, Double monto) {
       this.tipoPago = tipoPago;
       this.visita = visita;
       this.monto = monto;
    }
   
    public Integer getPagoCodigo() {
        return this.pagoCodigo;
    }
    
    public void setPagoCodigo(Integer pagoCodigo) {
        this.pagoCodigo = pagoCodigo;
    }
    public TipoPago getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(TipoPago tipoPago) {
        this.tipoPago = tipoPago;
    }
    public Visita getVisita() {
        return this.visita;
    }
    
    public void setVisita(Visita visita) {
        this.visita = visita;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }




}


