package com.gusedu.model;
// Generated 15/09/2015 11:54:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Par generated by hbm2java
 */
public class Par  implements java.io.Serializable {


     private Integer parCodigo;
     private Grupo grupo;
     private Punto puntoByPunCodigoP2;
     private Punto puntoByPunCodigoP1;
     private String parDescripcion;
     private String parPatogeno;
     private String parUrl;
     private Set enfermedadPars = new HashSet(0);
     private Set sintomaPars = new HashSet(0);
     private Set terapiaPars = new HashSet(0);

    public Par() {
    }

    public Par(Grupo grupo, Punto puntoByPunCodigoP2, Punto puntoByPunCodigoP1, String parDescripcion, String parPatogeno, String parUrl, Set enfermedadPars, Set sintomaPars, Set terapiaPars) {
       this.grupo = grupo;
       this.puntoByPunCodigoP2 = puntoByPunCodigoP2;
       this.puntoByPunCodigoP1 = puntoByPunCodigoP1;
       this.parDescripcion = parDescripcion;
       this.parPatogeno = parPatogeno;
       this.parUrl = parUrl;
       this.enfermedadPars = enfermedadPars;
       this.sintomaPars = sintomaPars;
       this.terapiaPars = terapiaPars;
    }
   
    public Integer getParCodigo() {
        return this.parCodigo;
    }
    
    public void setParCodigo(Integer parCodigo) {
        this.parCodigo = parCodigo;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Punto getPuntoByPunCodigoP2() {
        return this.puntoByPunCodigoP2;
    }
    
    public void setPuntoByPunCodigoP2(Punto puntoByPunCodigoP2) {
        this.puntoByPunCodigoP2 = puntoByPunCodigoP2;
    }
    public Punto getPuntoByPunCodigoP1() {
        return this.puntoByPunCodigoP1;
    }
    
    public void setPuntoByPunCodigoP1(Punto puntoByPunCodigoP1) {
        this.puntoByPunCodigoP1 = puntoByPunCodigoP1;
    }
    public String getParDescripcion() {
        return this.parDescripcion;
    }
    
    public void setParDescripcion(String parDescripcion) {
        this.parDescripcion = parDescripcion;
    }
    public String getParPatogeno() {
        return this.parPatogeno;
    }
    
    public void setParPatogeno(String parPatogeno) {
        this.parPatogeno = parPatogeno;
    }
    public String getParUrl() {
        return this.parUrl;
    }
    
    public void setParUrl(String parUrl) {
        this.parUrl = parUrl;
    }
    public Set getEnfermedadPars() {
        return this.enfermedadPars;
    }
    
    public void setEnfermedadPars(Set enfermedadPars) {
        this.enfermedadPars = enfermedadPars;
    }
    public Set getSintomaPars() {
        return this.sintomaPars;
    }
    
    public void setSintomaPars(Set sintomaPars) {
        this.sintomaPars = sintomaPars;
    }
    public Set getTerapiaPars() {
        return this.terapiaPars;
    }
    
    public void setTerapiaPars(Set terapiaPars) {
        this.terapiaPars = terapiaPars;
    }




}


