package com.gusedu.model;
// Generated 18/02/2016 11:27:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Par generated by hbm2java
 */
public class Par  implements java.io.Serializable {


     private Integer parCodigo;
     private Grupo grupo;
     private Punto puntoByPunCodigoP2;
     private Punto puntoByPunCodigoP1;
     private String parDescripcion;
     private String parPatogeno;
     private String parUrl;
     private Set sintomaPars = new HashSet(0);
     private Set enfermedadPars = new HashSet(0);
     private Set sintomaPars_1 = new HashSet(0);
     private Set enfermedadPars_1 = new HashSet(0);
     private Set terapiaPars = new HashSet(0);
     private Set terapiaPars_1 = new HashSet(0);

    public Par() {
    }

    public Par(Grupo grupo, Punto puntoByPunCodigoP2, Punto puntoByPunCodigoP1, String parDescripcion, String parPatogeno, String parUrl, Set sintomaPars, Set enfermedadPars, Set sintomaPars_1, Set enfermedadPars_1, Set terapiaPars, Set terapiaPars_1) {
       this.grupo = grupo;
       this.puntoByPunCodigoP2 = puntoByPunCodigoP2;
       this.puntoByPunCodigoP1 = puntoByPunCodigoP1;
       this.parDescripcion = parDescripcion;
       this.parPatogeno = parPatogeno;
       this.parUrl = parUrl;
       this.sintomaPars = sintomaPars;
       this.enfermedadPars = enfermedadPars;
       this.sintomaPars_1 = sintomaPars_1;
       this.enfermedadPars_1 = enfermedadPars_1;
       this.terapiaPars = terapiaPars;
       this.terapiaPars_1 = terapiaPars_1;
    }
   
    public Integer getParCodigo() {
        return this.parCodigo;
    }
    
    public void setParCodigo(Integer parCodigo) {
        this.parCodigo = parCodigo;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Punto getPuntoByPunCodigoP2() {
        return this.puntoByPunCodigoP2;
    }
    
    public void setPuntoByPunCodigoP2(Punto puntoByPunCodigoP2) {
        this.puntoByPunCodigoP2 = puntoByPunCodigoP2;
    }
    public Punto getPuntoByPunCodigoP1() {
        return this.puntoByPunCodigoP1;
    }
    
    public void setPuntoByPunCodigoP1(Punto puntoByPunCodigoP1) {
        this.puntoByPunCodigoP1 = puntoByPunCodigoP1;
    }
    public String getParDescripcion() {
        return this.parDescripcion;
    }
    
    public void setParDescripcion(String parDescripcion) {
        this.parDescripcion = parDescripcion;
    }
    public String getParPatogeno() {
        return this.parPatogeno;
    }
    
    public void setParPatogeno(String parPatogeno) {
        this.parPatogeno = parPatogeno;
    }
    public String getParUrl() {
        return this.parUrl;
    }
    
    public void setParUrl(String parUrl) {
        this.parUrl = parUrl;
    }
    public Set getSintomaPars() {
        return this.sintomaPars;
    }
    
    public void setSintomaPars(Set sintomaPars) {
        this.sintomaPars = sintomaPars;
    }
    public Set getEnfermedadPars() {
        return this.enfermedadPars;
    }
    
    public void setEnfermedadPars(Set enfermedadPars) {
        this.enfermedadPars = enfermedadPars;
    }
    public Set getSintomaPars_1() {
        return this.sintomaPars_1;
    }
    
    public void setSintomaPars_1(Set sintomaPars_1) {
        this.sintomaPars_1 = sintomaPars_1;
    }
    public Set getEnfermedadPars_1() {
        return this.enfermedadPars_1;
    }
    
    public void setEnfermedadPars_1(Set enfermedadPars_1) {
        this.enfermedadPars_1 = enfermedadPars_1;
    }
    public Set getTerapiaPars() {
        return this.terapiaPars;
    }
    
    public void setTerapiaPars(Set terapiaPars) {
        this.terapiaPars = terapiaPars;
    }
    public Set getTerapiaPars_1() {
        return this.terapiaPars_1;
    }
    
    public void setTerapiaPars_1(Set terapiaPars_1) {
        this.terapiaPars_1 = terapiaPars_1;
    }




}


