package com.gusedu.model;
// Generated 18/02/2016 11:27:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer perCodigo;
     private String perApellidoM;
     private String perApellidoP;
     private String perEnteroGusedu;
     private String perCorreo;
     private String perDni;
     private Boolean perCliPotencial;
     private String perEstadoCivil;
     private Date perFecCreacion;
     private Date perFecNacimiento;
     private Integer perNit;
     private String perNombres;
     private String perSexo;
     private String perSignoZodiacal;
     private String perTelFijo;
     private String perTelMovil;
     private String perUsuCreacion;
     private String perFacebook;
     private int perEdad;
     private String perDireccion;
     private Integer perDepartamento;
     private Integer perProvincia;
     private Integer perDistrito;
     private Set clientes = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set llamadas = new HashSet(0);
     private Set llamadas_1 = new HashSet(0);
     private Set usuarios_1 = new HashSet(0);
     private Set clientes_1 = new HashSet(0);

    public Persona() {
    }

	
    public Persona(String perApellidoM, String perApellidoP, String perNombres, int perEdad) {
        this.perApellidoM = perApellidoM;
        this.perApellidoP = perApellidoP;
        this.perNombres = perNombres;
        this.perEdad = perEdad;
    }
    public Persona(String perApellidoM, String perApellidoP, String perEnteroGusedu, String perCorreo, String perDni, Boolean perCliPotencial, String perEstadoCivil, Date perFecCreacion, Date perFecNacimiento, Integer perNit, String perNombres, String perSexo, String perSignoZodiacal, String perTelFijo, String perTelMovil, String perUsuCreacion, String perFacebook, int perEdad, String perDireccion, Integer perDepartamento, Integer perProvincia, Integer perDistrito, Set clientes, Set usuarios, Set llamadas, Set llamadas_1, Set usuarios_1, Set clientes_1) {
       this.perApellidoM = perApellidoM;
       this.perApellidoP = perApellidoP;
       this.perEnteroGusedu = perEnteroGusedu;
       this.perCorreo = perCorreo;
       this.perDni = perDni;
       this.perCliPotencial = perCliPotencial;
       this.perEstadoCivil = perEstadoCivil;
       this.perFecCreacion = perFecCreacion;
       this.perFecNacimiento = perFecNacimiento;
       this.perNit = perNit;
       this.perNombres = perNombres;
       this.perSexo = perSexo;
       this.perSignoZodiacal = perSignoZodiacal;
       this.perTelFijo = perTelFijo;
       this.perTelMovil = perTelMovil;
       this.perUsuCreacion = perUsuCreacion;
       this.perFacebook = perFacebook;
       this.perEdad = perEdad;
       this.perDireccion = perDireccion;
       this.perDepartamento = perDepartamento;
       this.perProvincia = perProvincia;
       this.perDistrito = perDistrito;
       this.clientes = clientes;
       this.usuarios = usuarios;
       this.llamadas = llamadas;
       this.llamadas_1 = llamadas_1;
       this.usuarios_1 = usuarios_1;
       this.clientes_1 = clientes_1;
    }
   
    public Integer getPerCodigo() {
        return this.perCodigo;
    }
    
    public void setPerCodigo(Integer perCodigo) {
        this.perCodigo = perCodigo;
    }
    public String getPerApellidoM() {
        return this.perApellidoM;
    }
    
    public void setPerApellidoM(String perApellidoM) {
        this.perApellidoM = perApellidoM;
    }
    public String getPerApellidoP() {
        return this.perApellidoP;
    }
    
    public void setPerApellidoP(String perApellidoP) {
        this.perApellidoP = perApellidoP;
    }
    public String getPerEnteroGusedu() {
        return this.perEnteroGusedu;
    }
    
    public void setPerEnteroGusedu(String perEnteroGusedu) {
        this.perEnteroGusedu = perEnteroGusedu;
    }
    public String getPerCorreo() {
        return this.perCorreo;
    }
    
    public void setPerCorreo(String perCorreo) {
        this.perCorreo = perCorreo;
    }
    public String getPerDni() {
        return this.perDni;
    }
    
    public void setPerDni(String perDni) {
        this.perDni = perDni;
    }
    public Boolean getPerCliPotencial() {
        return this.perCliPotencial;
    }
    
    public void setPerCliPotencial(Boolean perCliPotencial) {
        this.perCliPotencial = perCliPotencial;
    }
    public String getPerEstadoCivil() {
        return this.perEstadoCivil;
    }
    
    public void setPerEstadoCivil(String perEstadoCivil) {
        this.perEstadoCivil = perEstadoCivil;
    }
    public Date getPerFecCreacion() {
        return this.perFecCreacion;
    }
    
    public void setPerFecCreacion(Date perFecCreacion) {
        this.perFecCreacion = perFecCreacion;
    }
    public Date getPerFecNacimiento() {
        return this.perFecNacimiento;
    }
    
    public void setPerFecNacimiento(Date perFecNacimiento) {
        this.perFecNacimiento = perFecNacimiento;
    }
    public Integer getPerNit() {
        return this.perNit;
    }
    
    public void setPerNit(Integer perNit) {
        this.perNit = perNit;
    }
    public String getPerNombres() {
        return this.perNombres;
    }
    
    public void setPerNombres(String perNombres) {
        this.perNombres = perNombres;
    }
    public String getPerSexo() {
        return this.perSexo;
    }
    
    public void setPerSexo(String perSexo) {
        this.perSexo = perSexo;
    }
    public String getPerSignoZodiacal() {
        return this.perSignoZodiacal;
    }
    
    public void setPerSignoZodiacal(String perSignoZodiacal) {
        this.perSignoZodiacal = perSignoZodiacal;
    }
    public String getPerTelFijo() {
        return this.perTelFijo;
    }
    
    public void setPerTelFijo(String perTelFijo) {
        this.perTelFijo = perTelFijo;
    }
    public String getPerTelMovil() {
        return this.perTelMovil;
    }
    
    public void setPerTelMovil(String perTelMovil) {
        this.perTelMovil = perTelMovil;
    }
    public String getPerUsuCreacion() {
        return this.perUsuCreacion;
    }
    
    public void setPerUsuCreacion(String perUsuCreacion) {
        this.perUsuCreacion = perUsuCreacion;
    }
    public String getPerFacebook() {
        return this.perFacebook;
    }
    
    public void setPerFacebook(String perFacebook) {
        this.perFacebook = perFacebook;
    }
    public int getPerEdad() {
        return this.perEdad;
    }
    
    public void setPerEdad(int perEdad) {
        this.perEdad = perEdad;
    }
    public String getPerDireccion() {
        return this.perDireccion;
    }
    
    public void setPerDireccion(String perDireccion) {
        this.perDireccion = perDireccion;
    }
    public Integer getPerDepartamento() {
        return this.perDepartamento;
    }
    
    public void setPerDepartamento(Integer perDepartamento) {
        this.perDepartamento = perDepartamento;
    }
    public Integer getPerProvincia() {
        return this.perProvincia;
    }
    
    public void setPerProvincia(Integer perProvincia) {
        this.perProvincia = perProvincia;
    }
    public Integer getPerDistrito() {
        return this.perDistrito;
    }
    
    public void setPerDistrito(Integer perDistrito) {
        this.perDistrito = perDistrito;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getLlamadas() {
        return this.llamadas;
    }
    
    public void setLlamadas(Set llamadas) {
        this.llamadas = llamadas;
    }
    public Set getLlamadas_1() {
        return this.llamadas_1;
    }
    
    public void setLlamadas_1(Set llamadas_1) {
        this.llamadas_1 = llamadas_1;
    }
    public Set getUsuarios_1() {
        return this.usuarios_1;
    }
    
    public void setUsuarios_1(Set usuarios_1) {
        this.usuarios_1 = usuarios_1;
    }
    public Set getClientes_1() {
        return this.clientes_1;
    }
    
    public void setClientes_1(Set clientes_1) {
        this.clientes_1 = clientes_1;
    }




}


