package com.gusedu.model;
// Generated 18/02/2016 11:27:55 AM by Hibernate Tools 4.3.1



/**
 * ProductoVisita generated by hbm2java
 */
public class ProductoVisita  implements java.io.Serializable {


     private Integer pxvCodigo;
     private Producto producto;
     private Visita visita;
     private Double pxvCantidad;
     private Double pxvCostoParcial;
     private String pxvCurrencySymbol;

    public ProductoVisita() {
    }

	
    public ProductoVisita(Producto producto, Visita visita) {
        this.producto = producto;
        this.visita = visita;
    }
    public ProductoVisita(Producto producto, Visita visita, Double pxvCantidad, Double pxvCostoParcial, String pxvCurrencySymbol) {
       this.producto = producto;
       this.visita = visita;
       this.pxvCantidad = pxvCantidad;
       this.pxvCostoParcial = pxvCostoParcial;
       this.pxvCurrencySymbol = pxvCurrencySymbol;
    }
   
    public Integer getPxvCodigo() {
        return this.pxvCodigo;
    }
    
    public void setPxvCodigo(Integer pxvCodigo) {
        this.pxvCodigo = pxvCodigo;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Visita getVisita() {
        return this.visita;
    }
    
    public void setVisita(Visita visita) {
        this.visita = visita;
    }
    public Double getPxvCantidad() {
        return this.pxvCantidad;
    }
    
    public void setPxvCantidad(Double pxvCantidad) {
        this.pxvCantidad = pxvCantidad;
    }
    public Double getPxvCostoParcial() {
        return this.pxvCostoParcial;
    }
    
    public void setPxvCostoParcial(Double pxvCostoParcial) {
        this.pxvCostoParcial = pxvCostoParcial;
    }
    public String getPxvCurrencySymbol() {
        return this.pxvCurrencySymbol;
    }
    
    public void setPxvCurrencySymbol(String pxvCurrencySymbol) {
        this.pxvCurrencySymbol = pxvCurrencySymbol;
    }




}


