package com.gusedu.model;
// Generated 05/01/2016 05:20:55 PM by Hibernate Tools 4.3.1



/**
 * SintomaPar generated by hbm2java
 */
public class SintomaPar  implements java.io.Serializable {


     private Integer sxpCodigo;
     private Par par;
     private Sintoma sintoma;

    public SintomaPar() {
    }

    public SintomaPar(Par par, Sintoma sintoma) {
       this.par = par;
       this.sintoma = sintoma;
    }
   
    public Integer getSxpCodigo() {
        return this.sxpCodigo;
    }
    
    public void setSxpCodigo(Integer sxpCodigo) {
        this.sxpCodigo = sxpCodigo;
    }
    public Par getPar() {
        return this.par;
    }
    
    public void setPar(Par par) {
        this.par = par;
    }
    public Sintoma getSintoma() {
        return this.sintoma;
    }
    
    public void setSintoma(Sintoma sintoma) {
        this.sintoma = sintoma;
    }




}


