package com.gusedu.model;
// Generated 18/02/2016 11:27:55 AM by Hibernate Tools 4.3.1



/**
 * SintomaPar generated by hbm2java
 */
public class SintomaPar  implements java.io.Serializable {


     private Integer sxpCodigo;
     private Par par;
     private Sintoma sintoma;
     private String sxpDescripcion;

    public SintomaPar() {
    }

    public SintomaPar(Par par, Sintoma sintoma,String sxpDescripcion) {
       this.par = par;
       this.sintoma = sintoma;
       this.sxpDescripcion = sxpDescripcion;
    }
   
    public Integer getSxpCodigo() {
        return this.sxpCodigo;
    }
    
    public void setSxpCodigo(Integer sxpCodigo) {
        this.sxpCodigo = sxpCodigo;
    }
    public Par getPar() {
        return this.par;
    }
    
    public void setPar(Par par) {
        this.par = par;
    }
    public Sintoma getSintoma() {
        return this.sintoma;
    }
    
    public void setSintoma(Sintoma sintoma) {
        this.sintoma = sintoma;
    }

    public String getSxpDescripcion() {
        return sxpDescripcion;
    }

    public void setSxpDescripcion(String sxpDescripcion) {
        this.sxpDescripcion = sxpDescripcion;
    }
}


