package com.gusedu.model;
// Generated 15/09/2015 11:54:43 AM by Hibernate Tools 4.3.1



/**
 * SintomaVisita generated by hbm2java
 */
public class SintomaVisita  implements java.io.Serializable {


     private Integer sxvCodigo;
     private Sintoma sintoma;
     private Visita visita;
     private String sxvDescripcion;
     private Integer sxvDolor;

    public SintomaVisita() {
    }

	
    public SintomaVisita(Sintoma sintoma, Visita visita) {
        this.sintoma = sintoma;
        this.visita = visita;
    }
    public SintomaVisita(Sintoma sintoma, Visita visita, String sxvDescripcion, Integer sxvDolor) {
       this.sintoma = sintoma;
       this.visita = visita;
       this.sxvDescripcion = sxvDescripcion;
       this.sxvDolor = sxvDolor;
    }
   
    public Integer getSxvCodigo() {
        return this.sxvCodigo;
    }
    
    public void setSxvCodigo(Integer sxvCodigo) {
        this.sxvCodigo = sxvCodigo;
    }
    public Sintoma getSintoma() {
        return this.sintoma;
    }
    
    public void setSintoma(Sintoma sintoma) {
        this.sintoma = sintoma;
    }
    public Visita getVisita() {
        return this.visita;
    }
    
    public void setVisita(Visita visita) {
        this.visita = visita;
    }
    public String getSxvDescripcion() {
        return this.sxvDescripcion;
    }
    
    public void setSxvDescripcion(String sxvDescripcion) {
        this.sxvDescripcion = sxvDescripcion;
    }
    public Integer getSxvDolor() {
        return this.sxvDolor;
    }
    
    public void setSxvDolor(Integer sxvDolor) {
        this.sxvDolor = sxvDolor;
    }




}


