package com.gusedu.model;
// Generated 18/02/2016 11:27:55 AM by Hibernate Tools 4.3.1



/**
 * TerapiaSintoma generated by hbm2java
 */
public class TerapiaSintoma  implements java.io.Serializable {


     private Integer txsCodigo;
     private Sintoma sintoma;
     private Terapia terapia;
     private String txsComentario;
     private Boolean txsActivo;

    public TerapiaSintoma() {
    }

	
    public TerapiaSintoma(Sintoma sintoma, Terapia terapia) {
        this.sintoma = sintoma;
        this.terapia = terapia;
    }
    
    public TerapiaSintoma(Sintoma sintoma, Terapia terapia, String txsComentario,Boolean txsActivo) {
       this.sintoma = sintoma;
       this.terapia = terapia;
       this.txsComentario = txsComentario;
       this.txsActivo=txsActivo;
    }
   
    public Integer getTxsCodigo() {
        return this.txsCodigo;
    }
    
    public void setTxsCodigo(Integer txsCodigo) {
        this.txsCodigo = txsCodigo;
    }
    public Sintoma getSintoma() {
        return this.sintoma;
    }
    
    public void setSintoma(Sintoma sintoma) {
        this.sintoma = sintoma;
    }
    public Terapia getTerapia() {
        return this.terapia;
    }
    
    public void setTerapia(Terapia terapia) {
        this.terapia = terapia;
    }
    public String getTxsComentario() {
        return this.txsComentario;
    }
    
    public void setTxsComentario(String txsComentario) {
        this.txsComentario = txsComentario;
    }

    public Boolean getTxsActivo() {
        return txsActivo;
    }

    public void setTxsActivo(Boolean txsActivo) {
        this.txsActivo = txsActivo;
    }






}


