package com.gusedu.model;
// Generated 15/09/2015 11:54:43 AM by Hibernate Tools 4.3.1



/**
 * TerapiaPar generated by hbm2java
 */
public class TerapiaPar  implements java.io.Serializable {


     private Integer txpCodigo;
     private Par par;
     private Terapia terapia;
     private Boolean txpActivo;

    public TerapiaPar() {
    }

	
    public TerapiaPar(Par par, Terapia terapia) {
        this.par = par;
        this.terapia = terapia;
    }
    public TerapiaPar(Par par, Terapia terapia, Boolean txpActivo) {
       this.par = par;
       this.terapia = terapia;
       this.txpActivo = txpActivo;
    }
   
    public Integer getTxpCodigo() {
        return this.txpCodigo;
    }
    
    public void setTxpCodigo(Integer txpCodigo) {
        this.txpCodigo = txpCodigo;
    }
    public Par getPar() {
        return this.par;
    }
    
    public void setPar(Par par) {
        this.par = par;
    }
    public Terapia getTerapia() {
        return this.terapia;
    }
    
    public void setTerapia(Terapia terapia) {
        this.terapia = terapia;
    }
    public Boolean getTxpActivo() {
        return this.txpActivo;
    }
    
    public void setTxpActivo(Boolean txpActivo) {
        this.txpActivo = txpActivo;
    }




}


