package com.gusedu.model;
// Generated 05/01/2016 05:20:55 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Terapia generated by hbm2java
 */
public class Terapia  implements java.io.Serializable {


     private Integer terCodigo;
     private TipoTerapia tipoTerapia;
     private Visita visita;
     private String terDescripcion;
     private Date terFecProxima;
     private Date terFecRealizada;
     private String terUsuCreacion;
     private Double terCosto;
     private String terEmpresa;
     private Set enfermedadTerapias = new HashSet(0);
     private Set terapiaPars = new HashSet(0);
     private Set diagnosticos = new HashSet(0);
     private Set sintomaTerapias = new HashSet(0);
     private Set sintomaTerapias_1 = new HashSet(0);
     private Set enfermedadTerapias_1 = new HashSet(0);
     private Set diagnosticos_1 = new HashSet(0);
     private Set terapiaPars_1 = new HashSet(0);

    public Terapia() {
    }

	
    public Terapia(TipoTerapia tipoTerapia, Visita visita) {
        this.tipoTerapia = tipoTerapia;
        this.visita = visita;
    }
    public Terapia(TipoTerapia tipoTerapia, Visita visita, String terDescripcion, Date terFecProxima, Date terFecRealizada, String terUsuCreacion, Double terCosto, String terEmpresa, Set enfermedadTerapias, Set terapiaPars, Set diagnosticos, Set sintomaTerapias, Set sintomaTerapias_1, Set enfermedadTerapias_1, Set diagnosticos_1, Set terapiaPars_1) {
       this.tipoTerapia = tipoTerapia;
       this.visita = visita;
       this.terDescripcion = terDescripcion;
       this.terFecProxima = terFecProxima;
       this.terFecRealizada = terFecRealizada;
       this.terUsuCreacion = terUsuCreacion;
       this.terCosto = terCosto;
       this.terEmpresa = terEmpresa;
       this.enfermedadTerapias = enfermedadTerapias;
       this.terapiaPars = terapiaPars;
       this.diagnosticos = diagnosticos;
       this.sintomaTerapias = sintomaTerapias;
       this.sintomaTerapias_1 = sintomaTerapias_1;
       this.enfermedadTerapias_1 = enfermedadTerapias_1;
       this.diagnosticos_1 = diagnosticos_1;
       this.terapiaPars_1 = terapiaPars_1;
    }
   
    public Integer getTerCodigo() {
        return this.terCodigo;
    }
    
    public void setTerCodigo(Integer terCodigo) {
        this.terCodigo = terCodigo;
    }
    public TipoTerapia getTipoTerapia() {
        return this.tipoTerapia;
    }
    
    public void setTipoTerapia(TipoTerapia tipoTerapia) {
        this.tipoTerapia = tipoTerapia;
    }
    public Visita getVisita() {
        return this.visita;
    }
    
    public void setVisita(Visita visita) {
        this.visita = visita;
    }
    public String getTerDescripcion() {
        return this.terDescripcion;
    }
    
    public void setTerDescripcion(String terDescripcion) {
        this.terDescripcion = terDescripcion;
    }
    public Date getTerFecProxima() {
        return this.terFecProxima;
    }
    
    public void setTerFecProxima(Date terFecProxima) {
        this.terFecProxima = terFecProxima;
    }
    public Date getTerFecRealizada() {
        return this.terFecRealizada;
    }
    
    public void setTerFecRealizada(Date terFecRealizada) {
        this.terFecRealizada = terFecRealizada;
    }
    public String getTerUsuCreacion() {
        return this.terUsuCreacion;
    }
    
    public void setTerUsuCreacion(String terUsuCreacion) {
        this.terUsuCreacion = terUsuCreacion;
    }
    public Double getTerCosto() {
        return this.terCosto;
    }
    
    public void setTerCosto(Double terCosto) {
        this.terCosto = terCosto;
    }
    public String getTerEmpresa() {
        return this.terEmpresa;
    }
    
    public void setTerEmpresa(String terEmpresa) {
        this.terEmpresa = terEmpresa;
    }
    public Set getEnfermedadTerapias() {
        return this.enfermedadTerapias;
    }
    
    public void setEnfermedadTerapias(Set enfermedadTerapias) {
        this.enfermedadTerapias = enfermedadTerapias;
    }
    public Set getTerapiaPars() {
        return this.terapiaPars;
    }
    
    public void setTerapiaPars(Set terapiaPars) {
        this.terapiaPars = terapiaPars;
    }
    public Set getDiagnosticos() {
        return this.diagnosticos;
    }
    
    public void setDiagnosticos(Set diagnosticos) {
        this.diagnosticos = diagnosticos;
    }
    public Set getSintomaTerapias() {
        return this.sintomaTerapias;
    }
    
    public void setSintomaTerapias(Set sintomaTerapias) {
        this.sintomaTerapias = sintomaTerapias;
    }
    public Set getSintomaTerapias_1() {
        return this.sintomaTerapias_1;
    }
    
    public void setSintomaTerapias_1(Set sintomaTerapias_1) {
        this.sintomaTerapias_1 = sintomaTerapias_1;
    }
    public Set getEnfermedadTerapias_1() {
        return this.enfermedadTerapias_1;
    }
    
    public void setEnfermedadTerapias_1(Set enfermedadTerapias_1) {
        this.enfermedadTerapias_1 = enfermedadTerapias_1;
    }
    public Set getDiagnosticos_1() {
        return this.diagnosticos_1;
    }
    
    public void setDiagnosticos_1(Set diagnosticos_1) {
        this.diagnosticos_1 = diagnosticos_1;
    }
    public Set getTerapiaPars_1() {
        return this.terapiaPars_1;
    }
    
    public void setTerapiaPars_1(Set terapiaPars_1) {
        this.terapiaPars_1 = terapiaPars_1;
    }




}


