package com.gusedu.model;
// Generated 29/01/2016 10:00:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPago generated by hbm2java
 */
public class TipoPago  implements java.io.Serializable {


     private Integer tpagoCodigo;
     private String nombre;
     private Set pagos = new HashSet(0);

    public TipoPago() {
    }

    public TipoPago(String nombre, Set pagos) {
       this.nombre = nombre;
       this.pagos = pagos;
    }
   
    public Integer getTpagoCodigo() {
        return this.tpagoCodigo;
    }
    
    public void setTpagoCodigo(Integer tpagoCodigo) {
        this.tpagoCodigo = tpagoCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


