package com.gusedu.model;
// Generated 18/02/2016 11:27:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoProducto generated by hbm2java
 */
public class TipoProducto  implements java.io.Serializable {


     private Integer tprCodigo;
     private Date tprFecModificacion;
     private String tprNombre;
     private String tprUsuModificacion;
     private Set productos = new HashSet(0);
     private Set productos_1 = new HashSet(0);

    public TipoProducto() {
    }

    public TipoProducto(Date tprFecModificacion, String tprNombre, String tprUsuModificacion, Set productos, Set productos_1) {
       this.tprFecModificacion = tprFecModificacion;
       this.tprNombre = tprNombre;
       this.tprUsuModificacion = tprUsuModificacion;
       this.productos = productos;
       this.productos_1 = productos_1;
    }
   
    public Integer getTprCodigo() {
        return this.tprCodigo;
    }
    
    public void setTprCodigo(Integer tprCodigo) {
        this.tprCodigo = tprCodigo;
    }
    public Date getTprFecModificacion() {
        return this.tprFecModificacion;
    }
    
    public void setTprFecModificacion(Date tprFecModificacion) {
        this.tprFecModificacion = tprFecModificacion;
    }
    public String getTprNombre() {
        return this.tprNombre;
    }
    
    public void setTprNombre(String tprNombre) {
        this.tprNombre = tprNombre;
    }
    public String getTprUsuModificacion() {
        return this.tprUsuModificacion;
    }
    
    public void setTprUsuModificacion(String tprUsuModificacion) {
        this.tprUsuModificacion = tprUsuModificacion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }
    public Set getProductos_1() {
        return this.productos_1;
    }
    
    public void setProductos_1(Set productos_1) {
        this.productos_1 = productos_1;
    }




}


