package com.gusedu.model;
// Generated 05/01/2016 05:20:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoCliente generated by hbm2java
 */
public class TipoCliente  implements java.io.Serializable {


     private Integer tclCodigo;
     private String tclDescripcion;
     private Set clientes = new HashSet(0);
     private Set clientes_1 = new HashSet(0);

    public TipoCliente() {
    }

    public TipoCliente(String tclDescripcion, Set clientes, Set clientes_1) {
       this.tclDescripcion = tclDescripcion;
       this.clientes = clientes;
       this.clientes_1 = clientes_1;
    }
   
    public Integer getTclCodigo() {
        return this.tclCodigo;
    }
    
    public void setTclCodigo(Integer tclCodigo) {
        this.tclCodigo = tclCodigo;
    }
    public String getTclDescripcion() {
        return this.tclDescripcion;
    }
    
    public void setTclDescripcion(String tclDescripcion) {
        this.tclDescripcion = tclDescripcion;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getClientes_1() {
        return this.clientes_1;
    }
    
    public void setClientes_1(Set clientes_1) {
        this.clientes_1 = clientes_1;
    }




}


