package com.gusedu.model;
// Generated 15/09/2015 11:54:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private Integer tusCodigo;
     private String tusDescripcion;
     private Boolean caja;
     private Boolean datosPersonales;
     private Boolean historialTerapias;
     private Boolean historialVisitas;
     private Boolean consultaPares;
     private Boolean consultaParesPorEnfermedad;
     private Boolean consultaParesPorSintoma;
     private Boolean consultaPuntos;
     private Boolean crearVisita;
     private Boolean datosMedicos;
     private Boolean gestionCajaDiaria;
     private Boolean gestionEnfermedades;
     private Boolean gestionPares;
     private Boolean gestionPuntos;
     private Boolean gestionSintomas;
     private Boolean gestionTipoUsuarios;
     private Boolean gestionUsuarios;
     private Boolean historialVisita;
     private Boolean home;
     private Boolean registroTerapias;
     private Boolean reporteProducto;
     private Boolean reportePar;
     private Boolean ventaProductos;
     private Boolean registroTerapiaPares;
     private Boolean calendarioCitas;
     private Set usuarios = new HashSet(0);

    public TipoUsuario() {
    }

    public TipoUsuario(String tusDescripcion, Boolean caja, Boolean datosPersonales, Boolean historialTerapias, Boolean historialVisitas, Boolean consultaPares, Boolean consultaParesPorEnfermedad, Boolean consultaParesPorSintoma, Boolean consultaPuntos, Boolean crearVisita, Boolean datosMedicos, Boolean gestionCajaDiaria, Boolean gestionEnfermedades, Boolean gestionPares, Boolean gestionPuntos, Boolean gestionSintomas, Boolean gestionTipoUsuarios, Boolean gestionUsuarios, Boolean historialVisita, Boolean home, Boolean registroTerapias, Boolean reporteProducto, Boolean reportePar, Boolean ventaProductos, Boolean registroTerapiaPares, Boolean calendarioCitas, Set usuarios) {
       this.tusDescripcion = tusDescripcion;
       this.caja = caja;
       this.datosPersonales = datosPersonales;
       this.historialTerapias = historialTerapias;
       this.historialVisitas = historialVisitas;
       this.consultaPares = consultaPares;
       this.consultaParesPorEnfermedad = consultaParesPorEnfermedad;
       this.consultaParesPorSintoma = consultaParesPorSintoma;
       this.consultaPuntos = consultaPuntos;
       this.crearVisita = crearVisita;
       this.datosMedicos = datosMedicos;
       this.gestionCajaDiaria = gestionCajaDiaria;
       this.gestionEnfermedades = gestionEnfermedades;
       this.gestionPares = gestionPares;
       this.gestionPuntos = gestionPuntos;
       this.gestionSintomas = gestionSintomas;
       this.gestionTipoUsuarios = gestionTipoUsuarios;
       this.gestionUsuarios = gestionUsuarios;
       this.historialVisita = historialVisita;
       this.home = home;
       this.registroTerapias = registroTerapias;
       this.reporteProducto = reporteProducto;
       this.reportePar = reportePar;
       this.ventaProductos = ventaProductos;
       this.registroTerapiaPares = registroTerapiaPares;
       this.calendarioCitas=calendarioCitas;
       this.usuarios = usuarios;
    }
   
    public Integer getTusCodigo() {
        return this.tusCodigo;
    }
    
    public void setTusCodigo(Integer tusCodigo) {
        this.tusCodigo = tusCodigo;
    }
    public String getTusDescripcion() {
        return this.tusDescripcion;
    }
    
    public void setTusDescripcion(String tusDescripcion) {
        this.tusDescripcion = tusDescripcion;
    }
    public Boolean getCaja() {
        return this.caja;
    }
    
    public void setCaja(Boolean caja) {
        this.caja = caja;
    }
    public Boolean getDatosPersonales() {
        return this.datosPersonales;
    }
    
    public void setDatosPersonales(Boolean datosPersonales) {
        this.datosPersonales = datosPersonales;
    }
    public Boolean getHistorialTerapias() {
        return this.historialTerapias;
    }
    
    public void setHistorialTerapias(Boolean historialTerapias) {
        this.historialTerapias = historialTerapias;
    }
    public Boolean getHistorialVisitas() {
        return this.historialVisitas;
    }
    
    public void setHistorialVisitas(Boolean historialVisitas) {
        this.historialVisitas = historialVisitas;
    }
    public Boolean getConsultaPares() {
        return this.consultaPares;
    }
    
    public void setConsultaPares(Boolean consultaPares) {
        this.consultaPares = consultaPares;
    }
    public Boolean getConsultaParesPorEnfermedad() {
        return this.consultaParesPorEnfermedad;
    }
    
    public void setConsultaParesPorEnfermedad(Boolean consultaParesPorEnfermedad) {
        this.consultaParesPorEnfermedad = consultaParesPorEnfermedad;
    }
    public Boolean getConsultaParesPorSintoma() {
        return this.consultaParesPorSintoma;
    }
    
    public void setConsultaParesPorSintoma(Boolean consultaParesPorSintoma) {
        this.consultaParesPorSintoma = consultaParesPorSintoma;
    }
    public Boolean getConsultaPuntos() {
        return this.consultaPuntos;
    }
    
    public void setConsultaPuntos(Boolean consultaPuntos) {
        this.consultaPuntos = consultaPuntos;
    }
    public Boolean getCrearVisita() {
        return this.crearVisita;
    }
    
    public void setCrearVisita(Boolean crearVisita) {
        this.crearVisita = crearVisita;
    }
    public Boolean getDatosMedicos() {
        return this.datosMedicos;
    }
    
    public void setDatosMedicos(Boolean datosMedicos) {
        this.datosMedicos = datosMedicos;
    }
    public Boolean getGestionCajaDiaria() {
        return this.gestionCajaDiaria;
    }
    
    public void setGestionCajaDiaria(Boolean gestionCajaDiaria) {
        this.gestionCajaDiaria = gestionCajaDiaria;
    }
    public Boolean getGestionEnfermedades() {
        return this.gestionEnfermedades;
    }
    
    public void setGestionEnfermedades(Boolean gestionEnfermedades) {
        this.gestionEnfermedades = gestionEnfermedades;
    }
    public Boolean getGestionPares() {
        return this.gestionPares;
    }
    
    public void setGestionPares(Boolean gestionPares) {
        this.gestionPares = gestionPares;
    }
    public Boolean getGestionPuntos() {
        return this.gestionPuntos;
    }
    
    public void setGestionPuntos(Boolean gestionPuntos) {
        this.gestionPuntos = gestionPuntos;
    }
    public Boolean getGestionSintomas() {
        return this.gestionSintomas;
    }
    
    public void setGestionSintomas(Boolean gestionSintomas) {
        this.gestionSintomas = gestionSintomas;
    }
    public Boolean getGestionTipoUsuarios() {
        return this.gestionTipoUsuarios;
    }
    
    public void setGestionTipoUsuarios(Boolean gestionTipoUsuarios) {
        this.gestionTipoUsuarios = gestionTipoUsuarios;
    }
    public Boolean getGestionUsuarios() {
        return this.gestionUsuarios;
    }
    
    public void setGestionUsuarios(Boolean gestionUsuarios) {
        this.gestionUsuarios = gestionUsuarios;
    }
    public Boolean getHistorialVisita() {
        return this.historialVisita;
    }
    
    public void setHistorialVisita(Boolean historialVisita) {
        this.historialVisita = historialVisita;
    }
    public Boolean getHome() {
        return this.home;
    }
    
    public void setHome(Boolean home) {
        this.home = home;
    }
    public Boolean getRegistroTerapias() {
        return this.registroTerapias;
    }
    
    public void setRegistroTerapias(Boolean registroTerapias) {
        this.registroTerapias = registroTerapias;
    }
    public Boolean getReporteProducto() {
        return this.reporteProducto;
    }
    
    public void setReporteProducto(Boolean reporteProducto) {
        this.reporteProducto = reporteProducto;
    }
    public Boolean getReportePar() {
        return this.reportePar;
    }
    
    public void setReportePar(Boolean reportePar) {
        this.reportePar = reportePar;
    }
    public Boolean getVentaProductos() {
        return this.ventaProductos;
    }
    
    public void setVentaProductos(Boolean ventaProductos) {
        this.ventaProductos = ventaProductos;
    }
    public Boolean getRegistroTerapiaPares() {
        return this.registroTerapiaPares;
    }
    
    public void setRegistroTerapiaPares(Boolean registroTerapiaPares) {
        this.registroTerapiaPares = registroTerapiaPares;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

    public Boolean getCalendarioCitas() {
        return calendarioCitas;
    }

    public void setCalendarioCitas(Boolean calendarioCitas) {
        this.calendarioCitas = calendarioCitas;
    }




}


