package com.gusedu.model;
// Generated 18/02/2016 11:27:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoTerapia generated by hbm2java
 */
public class TipoTerapia  implements java.io.Serializable {


     private Integer tteCodigo;
     private Double tteCosto;
     private String tteCurrencySymbol;
     private Date tteFecModificacion;
     private String tteNombre;
     private String tteUsuModificacion;
     private Set terapias = new HashSet(0);
     private Set terapias_1 = new HashSet(0);

    public TipoTerapia() {
    }

    public TipoTerapia(Double tteCosto, String tteCurrencySymbol, Date tteFecModificacion, String tteNombre, String tteUsuModificacion, Set terapias, Set terapias_1) {
       this.tteCosto = tteCosto;
       this.tteCurrencySymbol = tteCurrencySymbol;
       this.tteFecModificacion = tteFecModificacion;
       this.tteNombre = tteNombre;
       this.tteUsuModificacion = tteUsuModificacion;
       this.terapias = terapias;
       this.terapias_1 = terapias_1;
    }
   
    public Integer getTteCodigo() {
        return this.tteCodigo;
    }
    
    public void setTteCodigo(Integer tteCodigo) {
        this.tteCodigo = tteCodigo;
    }
    public Double getTteCosto() {
        return this.tteCosto;
    }
    
    public void setTteCosto(Double tteCosto) {
        this.tteCosto = tteCosto;
    }
    public String getTteCurrencySymbol() {
        return this.tteCurrencySymbol;
    }
    
    public void setTteCurrencySymbol(String tteCurrencySymbol) {
        this.tteCurrencySymbol = tteCurrencySymbol;
    }
    public Date getTteFecModificacion() {
        return this.tteFecModificacion;
    }
    
    public void setTteFecModificacion(Date tteFecModificacion) {
        this.tteFecModificacion = tteFecModificacion;
    }
    public String getTteNombre() {
        return this.tteNombre;
    }
    
    public void setTteNombre(String tteNombre) {
        this.tteNombre = tteNombre;
    }
    public String getTteUsuModificacion() {
        return this.tteUsuModificacion;
    }
    
    public void setTteUsuModificacion(String tteUsuModificacion) {
        this.tteUsuModificacion = tteUsuModificacion;
    }
    public Set getTerapias() {
        return this.terapias;
    }
    
    public void setTerapias(Set terapias) {
        this.terapias = terapias;
    }
    public Set getTerapias_1() {
        return this.terapias_1;
    }
    
    public void setTerapias_1(Set terapias_1) {
        this.terapias_1 = terapias_1;
    }




}


