package com.gusedu.model;
// Generated 05/01/2016 05:20:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ubdepartamento generated by hbm2java
 */
public class Ubdepartamento  implements java.io.Serializable {


     private int idDepa;
     private String departamento;
     private Set ubprovincias = new HashSet(0);

    public Ubdepartamento() {
    }

	
    public Ubdepartamento(int idDepa) {
        this.idDepa = idDepa;
    }
    public Ubdepartamento(int idDepa, String departamento, Set ubprovincias) {
       this.idDepa = idDepa;
       this.departamento = departamento;
       this.ubprovincias = ubprovincias;
    }
   
    public int getIdDepa() {
        return this.idDepa;
    }
    
    public void setIdDepa(int idDepa) {
        this.idDepa = idDepa;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public Set getUbprovincias() {
        return this.ubprovincias;
    }
    
    public void setUbprovincias(Set ubprovincias) {
        this.ubprovincias = ubprovincias;
    }




}


