package com.gusedu.model;
// Generated 15/09/2015 11:54:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadMedida generated by hbm2java
 */
public class UnidadMedida  implements java.io.Serializable {


     private Integer umeCodigo;
     private String umeDescripcion;
     private Set productos = new HashSet(0);

    public UnidadMedida() {
    }

    public UnidadMedida(String umeDescripcion, Set productos) {
       this.umeDescripcion = umeDescripcion;
       this.productos = productos;
    }
   
    public Integer getUmeCodigo() {
        return this.umeCodigo;
    }
    
    public void setUmeCodigo(Integer umeCodigo) {
        this.umeCodigo = umeCodigo;
    }
    public String getUmeDescripcion() {
        return this.umeDescripcion;
    }
    
    public void setUmeDescripcion(String umeDescripcion) {
        this.umeDescripcion = umeDescripcion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


