package com.gusedu.model;
// Generated 29/01/2016 10:00:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadMedida generated by hbm2java
 */
public class UnidadMedida  implements java.io.Serializable {


     private Integer umeCodigo;
     private String umeDescripcion;
     private Set productos = new HashSet(0);
     private Set productos_1 = new HashSet(0);

    public UnidadMedida() {
    }

    public UnidadMedida(String umeDescripcion, Set productos, Set productos_1) {
       this.umeDescripcion = umeDescripcion;
       this.productos = productos;
       this.productos_1 = productos_1;
    }
   
    public Integer getUmeCodigo() {
        return this.umeCodigo;
    }
    
    public void setUmeCodigo(Integer umeCodigo) {
        this.umeCodigo = umeCodigo;
    }
    public String getUmeDescripcion() {
        return this.umeDescripcion;
    }
    
    public void setUmeDescripcion(String umeDescripcion) {
        this.umeDescripcion = umeDescripcion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }
    public Set getProductos_1() {
        return this.productos_1;
    }
    
    public void setProductos_1(Set productos_1) {
        this.productos_1 = productos_1;
    }




}


