package com.gusedu.model;
// Generated 18/02/2016 11:27:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer usuCodigo;
     private Persona persona;
     private TipoUsuario tipoUsuario;
     private Boolean usuActivo;
     private Date usuFecCreacion;
     private String usuPassword;
     private String usuUsuario;
     private String usuEmpresa;
     private Date usuFecFinm;
     private Integer usuPrecio;
     private Set mensajesForUsuCodigoReceptor = new HashSet(0);
     private Set mensajesForUsuCodigoReceptor_1 = new HashSet(0);
     private Set mensajesForUsuCodigoEmisor = new HashSet(0);
     private Set mensajesForUsuCodigoEmisor_1 = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(TipoUsuario tipoUsuario, String usuPassword, String usuUsuario) {
        this.tipoUsuario = tipoUsuario;
        this.usuPassword = usuPassword;
        this.usuUsuario = usuUsuario;
    }
    public Usuario(Persona persona, TipoUsuario tipoUsuario, Boolean usuActivo, Date usuFecCreacion, String usuPassword, String usuUsuario, String usuEmpresa, Date usuFecFinm, Integer usuPrecio, Set mensajesForUsuCodigoReceptor, Set mensajesForUsuCodigoReceptor_1, Set mensajesForUsuCodigoEmisor, Set mensajesForUsuCodigoEmisor_1) {
       this.persona = persona;
       this.tipoUsuario = tipoUsuario;
       this.usuActivo = usuActivo;
       this.usuFecCreacion = usuFecCreacion;
       this.usuPassword = usuPassword;
       this.usuUsuario = usuUsuario;
       this.usuEmpresa = usuEmpresa;
       this.usuFecFinm = usuFecFinm;
       this.usuPrecio = usuPrecio;
       this.mensajesForUsuCodigoReceptor = mensajesForUsuCodigoReceptor;
       this.mensajesForUsuCodigoReceptor_1 = mensajesForUsuCodigoReceptor_1;
       this.mensajesForUsuCodigoEmisor = mensajesForUsuCodigoEmisor;
       this.mensajesForUsuCodigoEmisor_1 = mensajesForUsuCodigoEmisor_1;
    }
   
    public Integer getUsuCodigo() {
        return this.usuCodigo;
    }
    
    public void setUsuCodigo(Integer usuCodigo) {
        this.usuCodigo = usuCodigo;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Boolean getUsuActivo() {
        return this.usuActivo;
    }
    
    public void setUsuActivo(Boolean usuActivo) {
        this.usuActivo = usuActivo;
    }
    public Date getUsuFecCreacion() {
        return this.usuFecCreacion;
    }
    
    public void setUsuFecCreacion(Date usuFecCreacion) {
        this.usuFecCreacion = usuFecCreacion;
    }
    public String getUsuPassword() {
        return this.usuPassword;
    }
    
    public void setUsuPassword(String usuPassword) {
        this.usuPassword = usuPassword;
    }
    public String getUsuUsuario() {
        return this.usuUsuario;
    }
    
    public void setUsuUsuario(String usuUsuario) {
        this.usuUsuario = usuUsuario;
    }
    public String getUsuEmpresa() {
        return this.usuEmpresa;
    }
    
    public void setUsuEmpresa(String usuEmpresa) {
        this.usuEmpresa = usuEmpresa;
    }
    public Date getUsuFecFinm() {
        return this.usuFecFinm;
    }
    
    public void setUsuFecFinm(Date usuFecFinm) {
        this.usuFecFinm = usuFecFinm;
    }
    public Integer getUsuPrecio() {
        return this.usuPrecio;
    }
    
    public void setUsuPrecio(Integer usuPrecio) {
        this.usuPrecio = usuPrecio;
    }
    public Set getMensajesForUsuCodigoReceptor() {
        return this.mensajesForUsuCodigoReceptor;
    }
    
    public void setMensajesForUsuCodigoReceptor(Set mensajesForUsuCodigoReceptor) {
        this.mensajesForUsuCodigoReceptor = mensajesForUsuCodigoReceptor;
    }
    public Set getMensajesForUsuCodigoReceptor_1() {
        return this.mensajesForUsuCodigoReceptor_1;
    }
    
    public void setMensajesForUsuCodigoReceptor_1(Set mensajesForUsuCodigoReceptor_1) {
        this.mensajesForUsuCodigoReceptor_1 = mensajesForUsuCodigoReceptor_1;
    }
    public Set getMensajesForUsuCodigoEmisor() {
        return this.mensajesForUsuCodigoEmisor;
    }
    
    public void setMensajesForUsuCodigoEmisor(Set mensajesForUsuCodigoEmisor) {
        this.mensajesForUsuCodigoEmisor = mensajesForUsuCodigoEmisor;
    }
    public Set getMensajesForUsuCodigoEmisor_1() {
        return this.mensajesForUsuCodigoEmisor_1;
    }
    
    public void setMensajesForUsuCodigoEmisor_1(Set mensajesForUsuCodigoEmisor_1) {
        this.mensajesForUsuCodigoEmisor_1 = mensajesForUsuCodigoEmisor_1;
    }




}


