package com.gusedu.model;
// Generated 18/02/2016 11:27:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Visita generated by hbm2java
 */
public class Visita  implements java.io.Serializable {


     private Integer visCodigo;
     private Cliente cliente;
     private Double visCostoTotal;
     private Boolean visPresencial;
     private Integer visEstado;
     private Date visFecCreacion;
     private Integer visPrioridad;
     private String visUsuCreacion;
     private String visDescripcion;
     private Date visFecFin;
     private boolean visLlegada;
     private Set enfermedadVisitas = new HashSet(0);
     private Set sintomaVisitas = new HashSet(0);
     private Set productoVisitas = new HashSet(0);
     private Set terapias = new HashSet(0);
     private Set terapias_1 = new HashSet(0);
     private Set pagos = new HashSet(0);
     private Set productoVisitas_1 = new HashSet(0);
     private Set enfermedadVisitas_1 = new HashSet(0);
     private Set sintomaVisitas_1 = new HashSet(0);
     private Set historiaClinicas = new HashSet(0);
     private Set historiaClinicas_1 = new HashSet(0);

    public Visita() {
    }

	
    public Visita(Cliente cliente) {
        this.cliente = cliente;
    }

    public Visita(Integer visCodigo, Cliente cliente, Double visCostoTotal, Boolean visPresencial, Integer visEstado, Date visFecCreacion, Integer visPrioridad, String visUsuCreacion, String visDescripcion, Date visFecFin, boolean visLlegada) {
        this.visCodigo = visCodigo;
        this.cliente = cliente;
        this.visCostoTotal = visCostoTotal;
        this.visPresencial = visPresencial;
        this.visEstado = visEstado;
        this.visFecCreacion = visFecCreacion;
        this.visPrioridad = visPrioridad;
        this.visUsuCreacion = visUsuCreacion;
        this.visDescripcion = visDescripcion;
        this.visFecFin = visFecFin;
        this.visLlegada = visLlegada;
    }

   
    public Integer getVisCodigo() {
        return this.visCodigo;
    }
    
    public void setVisCodigo(Integer visCodigo) {
        this.visCodigo = visCodigo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Double getVisCostoTotal() {
        return this.visCostoTotal;
    }
    
    public void setVisCostoTotal(Double visCostoTotal) {
        this.visCostoTotal = visCostoTotal;
    }
    public Boolean getVisPresencial() {
        return this.visPresencial;
    }
    
    public void setVisPresencial(Boolean visPresencial) {
        this.visPresencial = visPresencial;
    }
    public Integer getVisEstado() {
        return this.visEstado;
    }
    
    public void setVisEstado(Integer visEstado) {
        this.visEstado = visEstado;
    }
    public Date getVisFecCreacion() {
        return this.visFecCreacion;
    }
    
    public void setVisFecCreacion(Date visFecCreacion) {
        this.visFecCreacion = visFecCreacion;
    }
    public Integer getVisPrioridad() {
        return this.visPrioridad;
    }
    
    public void setVisPrioridad(Integer visPrioridad) {
        this.visPrioridad = visPrioridad;
    }
    public String getVisUsuCreacion() {
        return this.visUsuCreacion;
    }
    
    public void setVisUsuCreacion(String visUsuCreacion) {
        this.visUsuCreacion = visUsuCreacion;
    }
    public String getVisDescripcion() {
        return this.visDescripcion;
    }
    
    public void setVisDescripcion(String visDescripcion) {
        this.visDescripcion = visDescripcion;
    }
    public Date getVisFecFin() {
        return this.visFecFin;
    }
    
    public void setVisFecFin(Date visFecFin) {
        this.visFecFin = visFecFin;
    }

    public boolean isVisLlegada() {
        return visLlegada;
    }

    public void setVisLlegada(boolean visLlegada) {
        this.visLlegada = visLlegada;
    }
    
    
    
    public Set getEnfermedadVisitas() {
        return this.enfermedadVisitas;
    }
    
    public void setEnfermedadVisitas(Set enfermedadVisitas) {
        this.enfermedadVisitas = enfermedadVisitas;
    }
    public Set getSintomaVisitas() {
        return this.sintomaVisitas;
    }
    
    public void setSintomaVisitas(Set sintomaVisitas) {
        this.sintomaVisitas = sintomaVisitas;
    }
    public Set getProductoVisitas() {
        return this.productoVisitas;
    }
    
    public void setProductoVisitas(Set productoVisitas) {
        this.productoVisitas = productoVisitas;
    }
    public Set getTerapias() {
        return this.terapias;
    }
    
    public void setTerapias(Set terapias) {
        this.terapias = terapias;
    }
    public Set getTerapias_1() {
        return this.terapias_1;
    }
    
    public void setTerapias_1(Set terapias_1) {
        this.terapias_1 = terapias_1;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }
    public Set getProductoVisitas_1() {
        return this.productoVisitas_1;
    }
    
    public void setProductoVisitas_1(Set productoVisitas_1) {
        this.productoVisitas_1 = productoVisitas_1;
    }
    public Set getEnfermedadVisitas_1() {
        return this.enfermedadVisitas_1;
    }
    
    public void setEnfermedadVisitas_1(Set enfermedadVisitas_1) {
        this.enfermedadVisitas_1 = enfermedadVisitas_1;
    }
    public Set getSintomaVisitas_1() {
        return this.sintomaVisitas_1;
    }
    
    public void setSintomaVisitas_1(Set sintomaVisitas_1) {
        this.sintomaVisitas_1 = sintomaVisitas_1;
    }
    public Set getHistoriaClinicas() {
        return this.historiaClinicas;
    }
    
    public void setHistoriaClinicas(Set historiaClinicas) {
        this.historiaClinicas = historiaClinicas;
    }
    public Set getHistoriaClinicas_1() {
        return this.historiaClinicas_1;
    }
    
    public void setHistoriaClinicas_1(Set historiaClinicas_1) {
        this.historiaClinicas_1 = historiaClinicas_1;
    }




}


